services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: diwdemo
      POSTGRES_PASSWORD: diwdemo
      POSTGRES_DB: diw-demo
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db

volumes:
  db-data:
